# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: keinorg
# "service" is the name of this project. This will also be added to your AWS resource names.
service: fidel-api-lite

stages:
  default:
    params:
      locationsTableName: "locations-table-${sls:stage}"
      offersTableName: "offers-table-${sls:stage}"
      offerLocationsTableName: "offer-locations-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource:
            - Fn::GetAtt: [LocationsTable, Arn]
            - Fn::GetAtt: [OffersTable, Arn]
            - Fn::GetAtt: [OfferLocationsTable, Arn]
  environment:
    LOCATIONS_TABLE: ${param:locationsTableName}
    OFFERS_TABLE: ${param:offersTableName}
    OFFER_LOCATIONS_TABLE: ${param:offerLocationsTableName}

functions:
  linkOffersToLocations:
    handler: offerLocations.link

resources:
  Resources:
    LocationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:locationsTableName}
    OffersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:offersTableName}
    OfferLocationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: offerId
            AttributeType: S
          - AttributeName: locationId
            AttributeType: S
        KeySchema:
          - AttributeName: offerId
            KeyType: HASH
          - AttributeName: locationId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:offerLocationsTableName}
